// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkbsauietlsnodewufoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrYnNhdWlldGxzbm9kZXd1Zm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTcyOTUsImV4cCI6MjA2ODkzMzI5NX0.sET2Ha4e1qR3kkBuJrJuQPPgQGFQIB1tDDJAKUrY9IE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});