// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yufaogxbadzxmvyrbmez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZmFvZ3hiYWR6eG12eXJibWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDkwMzYsImV4cCI6MjA3MjI4NTAzNn0.aP4w8HQuhOso1SVPMEhaTrKEpjpHqWnkXC2f0BzNXOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});