// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfgkrghsteyvhtehlyfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmZ2tyZ2hzdGV5dmh0ZWhseWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTI1OTEsImV4cCI6MjA3NTMyODU5MX0.KNVld2MCKwkuq1MpjeWof6KoAvkrxqwsEFLnV_Xu7Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});